[package]
name = "logger"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
flexi_logger = { version = "0.31", features = ["json", "async"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
encoding_rs = "0.8"

[lib]
crate-type = ["rlib"]