[package]
name = "logger"
version = "0.1.0"
edition = "2024"

[dependencies]
flexi_logger = "0.31"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = { version = "1.21", features = ["default"] }
tokio = { version = "1.48", features = ["full"] }